from typing import (Dict, List, Any, Type, )
from warnings import deprecated

from PySide6.QtCore import (
    QAbstractTableModel, 
    )

from openpyxl import (Workbook, load_workbook, )
from openpyxl.styles import PatternFill, Font, fills, colors
from openpyxl.utils.datetime import from_excel, WINDOWS_EPOCH

from .cQModels import (SQLAlchemyTableModel, )
from ..database import Repository

ExcelWorkbook_fileext = ".XLSX"

class cExcelFile(Workbook):
    """Subclass of openpyxl's Workbook to add custom functionality for Excel file handling."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Additional initialization can be added here if needed
    

    def load_from_fromqs(self,
        qset:SQLAlchemyTableModel|List[Dict[str, Any]], 
        wsName:str|None = None,
        freezecols:int = 0, 
        ) -> bool:
        """
        qset: a QAbstractTableModel or list of dictionaries
        flName: the name of the file to be built (WITHOUT extension!).  It's stored on the server.  If it's to be dl'd, the caller does that
        freezecols = 0: the number of columns to freeze to the left
        The top row contains the field names, is always frozen, is bold and is shaded grey

        Returns True if the workbook was successfully populated from the qset, False otherwise.
        """

        # far easier to process a list of dictionaries, so...
        if isinstance(qset,QAbstractTableModel):
            # make this a util
            qlist = qset.getDataAsList()
        elif isinstance(qset,list):
            qlist = qset
        else:
            return False
        if qlist:
            if not isinstance(qlist[0],dict):
                # review this later ...
                try:
                    qlist = [n.__dict__ for n in qlist]
                except:
                    qlist = []

        # create empty workbook with an empty worksheet
        wb = self
        ws = wb.create_sheet(title=wsName)

        # header row is names of columns
        if qlist:
            fields = list(qlist[0])
            ws.append(fields)

            # append each row
            for row in qlist:
                ws.append(list(row.values())) # type: ignore

            # make header row bold, shade it grey, freeze it
            # ws.show_gridlines = True  #Nope - this is a R/O attribute
            for cell in ws[1]: # type: ignore
                cell.font = Font(bold=True)
                cell.fill = PatternFill(fill_type=fills.FILL_SOLID,
                                start_color=colors.Color("00808080"),
                                end_color=colors.Color("00808080")
                                )
            #TODO: convert row1 and cols:freezecols to an address (A=0, B=1, C=2 etc) for line below
            ws.freeze_panes ='A2'
            #TODO: if freezecols passed, freeze them, too
        #endif qlist

        return True
    # fromqs

    def load_from_file(self, filename: str, *args, **kwargs) -> bool:
        """Load an existing Excel file into the workbook.
        
        Args:
            filename (str): The name of the file to load, including extension.
            For other argumewnts, see openpyxl.reader.excel.load_workbook() documentation.
        
        Returns:
            True if the file was successfully loaded, False otherwise.
        """
        try:
            self = load_workbook(filename, *args, **kwargs)
            return True
        except Exception as e:
            print(f"Error loading file {filename}: {e}")
            return False        
    # load_from_file

    def save_to_db(self, dbsession, TargetModel, wsName:str|None = None):
        """Save the workbook data to a database using the provided session and target model.
        
        Args:
            dbsession: Database session for saving the data.
            TargetModel: The target ORM model class for the spreadsheet data.
            wsName: Name of the worksheet to save from. If None, the active worksheet will be used.
            
        Note:
            This method is not yet implemented and should be overridden in subclasses
            to provide specific logic for saving the workbook data to the database.
        """
        pass
    # save_to_db
    
    # # generated by AI - review and edit as needed
    # def save_with_extension(self, filename: str):
    #     """Save the workbook with the specified filename, ensuring it has the correct extension.
        
    #     Args:
    #         filename (str): The name of the file to save, without extension.
    #     """
    #     if not filename.endswith(ExcelWorkbook_fileext):
    #         filename += ExcelWorkbook_fileext
    #     self.save(filename)
# cExcelFile
    def end_of_class(self):
        """Placeholder method to indicate the end of the cExcelFile class definition."""
        pass

# absorb into above class (#12)
@deprecated("Use cExcelFile class instead of this function.  This function will be removed in a future release.")
def Excelfile_fromqs(qset:SQLAlchemyTableModel|List[Dict[str, Any]], flName:str|None = None,
                     freezecols:int = 0, returnFileName: bool = False) -> Workbook|str:
    """
    qset: a QAbstractTableModel or list of dictionaries
    flName: the name of the file to be built (WITHOUT extension!).  It's stored on the server.  If it's to be dl'd, the caller does that
    freezecols = 0: the number of columns to freeze to the left
    The top row contains the field names, is always frozen, is bold and is shaded grey

    used to Return the name of the Workbook file (with extension).  Once I start building in errorchecking and exceptions, other returns may be possible
    Returns the Workbook file (with extension)
    """

    # far easier to process a list of dictionaries, so...
    if isinstance(qset,QAbstractTableModel):
        # make this a util
        qlist = qset.getDataAsList()
    elif isinstance(qset,list):
        qlist = qset
    else:
        return None
    if qlist:
        if not isinstance(qlist[0],dict):
            # review this later ...
            try:
                qlist = [n.__dict__ for n in qlist]
            except:
                qlist = []

    # create empty workbook with an empty worksheet
    wb = Workbook()
    ws = wb.active
    if ws is None:
        ws = wb.create_sheet()

    # header row is names of columns
    if qlist:
        fields = list(qlist[0])
        ws.append(fields)

        # append each row
        for row in qlist:
            ws.append(list(row.values())) # type: ignore

        # make header row bold, shade it grey, freeze it
        # ws.show_gridlines = True  #Nope - this is a R/O attribute
        for cell in ws[1]: # type: ignore
            cell.font = Font(bold=True)
            cell.fill = PatternFill(fill_type=fills.FILL_SOLID,
                            start_color=colors.Color("00808080"),
                            end_color=colors.Color("00808080")
                            )
        #TODO: convert row1 and cols:freezecols to an address (A=0, B=1, C=2 etc) for line below
        ws.freeze_panes ='A2'
        #TODO: if freezecols passed, freeze them, too


    # save the workbook
    if flName:
        wb.save(flName+ExcelWorkbook_fileext)
    
    if returnFileName:
        # close the workbook
        wb.close()
        # and return file Name to the caller
        return (flName+ExcelWorkbook_fileext if flName else "")
    else:
        # return the workbook itself
        return wb
    #endif returnFileName


# move this into a method of the above class
class UpldSprdsheet():
    """Base class for handling spreadsheet uploads with field validation.
    
    This class provides functionality for processing uploaded spreadsheets,
    validating field types, and cleaning data according to defined rules.
    
    Attributes:
        TargetModel: The target ORM model class for the spreadsheet data.
        SprdsheetDateEpoch: Date epoch used for spreadsheet date conversion.
        SprdsheetFlds (dict): Dictionary mapping spreadsheet field names to field descriptors.
    """
    TargetModel = None
    SprdsheetDateEpoch = WINDOWS_EPOCH

    class SprdsheetFldDescriptor:
        """Descriptor for spreadsheet fields, defining validation rules and cleaning procedures."""
        """Create a field descriptor for spreadsheet field validation.
        
        Args:
            ModelFldName (str): The name of the field in the TargetModel.
            AllowedTypes: List of tuples (type, cleanproc) specifying allowed types
                and their cleaning procedures. Empty list if any string is allowed.
        
        Returns:
            dict: Field descriptor dictionary with ModelFldName and AllowedTypes.
        """
        def __init__(self, ModelFldName:str, AllowedTypes=None, CleanProc=None):
            self.ModelFldName:str = ModelFldName
            self.AllowedTypes:list = AllowedTypes if AllowedTypes is not None else []
            self.CleanProc = CleanProc
      # key will be the SprdsheetName, value is a SprdsheetFldDescriptor
    SprdsheetFlds:Dict[str,SprdsheetFldDescriptor] = {}  # key will be the SprdsheetName, value is a SprdsheetFldDescriptor
      # key will be the SprdsheetName, value is a SprdsheetFldDescriptor

    def cleanupfld(self, fld, val):
        """Clean and validate a field value according to its allowed types.
        
        Args:
            fld: Field name to clean.
            val: Value to clean and validate.
        
        Returns:
            tuple: (usefld, cleanval) where usefld is True if the field should be used,
                and cleanval is the cleaned value.
        """
        usefld = False
        cleanval = val
        
        if fld not in self.SprdsheetFlds:
            # just feed the value back
            usefld = True
            cleanval = val
            return usefld, cleanval
        # endif fld not in self.SprdsheetFlds
        
        cleanDesc = self.SprdsheetFlds[fld]
        if callable(cleanDesc.CleanProc):
            result = cleanDesc.CleanProc(val)
            if isinstance(result, tuple) and len(result) == 2:
                usefld, cleanval = result
            else:
                usefld = (result is not None)
                cleanval = result if usefld else None
        if not usefld:
            return usefld, cleanval
        # if callable(cleanDesc.CleanProc)
        
        if cleanDesc.AllowedTypes == []:
            usefld = (val is not None)
            if usefld: cleanval = str(val)
        else:
            usefld = any(isinstance(val, t) for t in cleanDesc.AllowedTypes)
        #endif cleanDesc.AllowedTypes == []
        
        return usefld, cleanval
    # cleanupfld

    def process_db_import(self, 
        ssnmaker, 
        TargetModel:Type[Any],
        SprsheetName, 
        flName, 
        SprdsheetFlds:Dict[str,SprdsheetFldDescriptor]|None = None, 
        required_columns=None,
        progress_interval=100,
        progress_callback = None
        ):
      # key will be the SprdsheetName, value is a SprdsheetFldDescriptor
        """Process the imported spreadsheet data and save it to the database.
        
        Args:
            dbsession: Database session for saving the processed data.
            SprsheetName: Name of the spreadsheet being processed.
            data: The data extracted from the spreadsheet to be processed.
            
        Note:
            This method is not yet implemented and should be overridden in subclasses
            to provide specific processing logic for the imported data.
        """
        wb = cExcelFile()
        if not wb.load_from_file(flName, read_only=True):
            print(f"Error loading file {flName}")
            return False
        
        if SprdsheetFlds is not None:
            self.SprdsheetFlds = SprdsheetFlds
        
        ws = wb[SprsheetName] if SprsheetName in wb.sheetnames else wb.active
        if ws is None:
            print(f"Worksheet {SprsheetName} not found in workbook.")
            return False
                
        SprshtHdrRow = ws[1]
        required_columns = required_columns if required_columns is not None else []
        dbFld_to_SsprshtCol:dict[str, Any] = {req_col: None for req_col in required_columns}
        for col in SprshtHdrRow:
            if col.value in self.SprdsheetFlds:
                colval = str(col.value)
                modlFldNm = self.SprdsheetFlds[colval].ModelFldName
                colIndx = (col.column or 0) - 1
                dbFld_to_SsprshtCol[modlFldNm] = colIndx
        # end for col in SprshtHdrRow
        
        if any(val is None for val in dbFld_to_SsprshtCol.values()):
            missing_cols = [col for col, val in dbFld_to_SsprshtCol.items() if val is None]
            print(f"Error: Missing required columns in spreadsheet: {', '.join(missing_cols)}")
            return False
        # end if any missing required columns
        
        # Process each row in the worksheet
        num_rows = ws.max_row
        nRows = 0
        for row in ws.iter_rows(min_row=2, values_only=True):
            nRows += 1
            if nRows % progress_interval == 0:
                print(f"Processing row {nRows} of {num_rows}...")
                if callable(progress_callback):
                    progress_callback(nRows, num_rows)
            # if nRows % progress_interval == 0
            record_data = {}
            for dbFld, colIndx in dbFld_to_SsprshtCol.items():
                if colIndx is not None and colIndx < len(row):
                    fld_name = next((fld for fld, desc in self.SprdsheetFlds.items() if desc.ModelFldName == dbFld), None)
                    if fld_name:
                        usefld, cleanval = self.cleanupfld(fld_name, row[colIndx])
                        if usefld:
                            record_data[dbFld] = cleanval
            # end for dbFld, colIndx in dbFld_to_SsprshtCol.items()
            
            # Here you would create an instance of TargetModel with record_data and add it to the session
            new_record = TargetModel(**record_data)
            Repository(ssnmaker, TargetModel).add(new_record)
        # for each row
    # process_db_import